### ISSUE TITLE
Binding is not working

### ISSUE THREAD

**Issue by hazemhagrass** [zeeshanhyder/angular-tag-cloud#1]
Hi,
How I can make "data" bindable? your plugin is loading only the first version of it
`<ng-tag-cloud cloud-width="250" cloud-height="250" cloud-data="data"></ng-tag-cloud>`

**Comment by zeeshanhyder** [comment]
Hello. I am a bit occupied at the moment but I will push the next version (which includes binding BTW) mostly by end of this week. This issue is in my next release list. Thanks for notifying.

**Comment by hazemhagrass** [comment]
Hi,
I did it and sent you pull request.

**Comment by zeeshanhyder** [comment]
Cool. Let me check and merge your code. Thanks.

**Comment by zeeshanhyder** [comment]
Resolved by this [commit](https://github.com/zeeshanhyder/angular-tag-cloud/commit/4ae4268671572ce4f5c23771eae399f03f706759)
