### ISSUE TITLE
On Hover?

### ISSUE THREAD

**Issue by aclowkey** [zeeshanhyder/angular-tag-cloud#13]
Is there a possibility to add onHover and display how many occurrences a word has ? 

Thanks

**Comment by zeeshanhyder** [comment]
@Alexettels Really sorry. This feature is not supported as of yet. Since this feature is very specific and might not fit the need in general so it may not be added soon. But if you want, you can fork and add it manually. :)

**Comment by aclowkey** [comment]
Thanks
