### ISSUE TITLE
Manage events

### ISSUE THREAD

**Issue by juanbenitopr** [zeeshanhyder/angular-tag-cloud#14]
Hi!,

Excuse me, someone knows how to manage the event when you click on some word?

thanks!

**Comment by manish-kumar9a9** [comment]
@juanbenitopr 
Did you able to short out the above issue?

**Comment by juanbenitopr** [comment]
Yes, I fixed it, I just modified the library to allow a "cloudClick", where you can pass a callback, but it is unstable, the project changed the requirements and I didn't have to use it finally.

You can try it from here:
https://github.com/juanbenitopr/angular-tag-cloud
