### ISSUE TITLE
Minification causes unknown provider error

### ISSUE THREAD

**Issue by wspresto** [zeeshanhyder/angular-tag-cloud#3]
Could you please provide a minified version that works within this repo?

**Comment by zeeshanhyder** [comment]
Hello. Thanks for letting know. I am out of station right now. I will get back in two days and start working on minified version.

**Comment by zeeshanhyder** [comment]
fixed by the commit https://github.com/zeeshanhyder/angular-tag-cloud/commit/011a7748f92862784becdb1ef28da132bc91761e
