### ISSUE TITLE
setting data source to an array that changes causes undefined

### ISSUE THREAD

**Issue by johnsonreyliu** [zeeshanhyder/angular-tag-cloud#7]
when i set data source to be an array that i build vs hard coded, the word cloud will just display undefined

i am reading values from a DB and then building the array. On load, the word cloud just says undefined for all elements

**Comment by zeeshanhyder** [comment]
Can you please post a codepen or pastebin of your issue? That would be really helpful for me. Thanks.

**Comment by johnsonreyliu** [comment]
all i did was create an array, add some values to it with {word, weight} and then assign that to the cloud data element

`<ng-tag-cloud cloud-width="250" cloud-height="250" cloud-data="adminCtrl.words"></ng-tag-cloud>`

<img width="371" alt="screenshot 2016-11-08 15 21 53" src="https://cloud.githubusercontent.com/assets/994620/20115666/22b80016-a5c7-11e6-8bba-77e56f3feb56.png">

**Comment by zeeshanhyder** [comment]
As specified here https://github.com/zeeshanhyder/angular-tag-cloud/blob/master/README.md#usage the object should have {text,weight} not {word,weight}.

**Comment by johnsonreyliu** [comment]
d'oh thank you :)
