### ISSUE TITLE
word cloud broken on safari desktop and mobile

### ISSUE THREAD

**Issue by johnsonreyliu** [zeeshanhyder/angular-tag-cloud#8]
I get this error on the latest safari version
<img width="393" alt="screenshot 2016-11-16 12 04 38" src="https://cloud.githubusercontent.com/assets/994620/20357172/e89eef82-abf4-11e6-9fa8-eb2536084d27.png">

The error is 

> Did not parse stylesheet at 'http://citipulse.mybluemix.net/node_modules/angular-tag-cloud/src/css/ng-tag-cloud.css' because non CSS MIME types are not allowed in strict mode.

and this is how it looks

Works fine on chrome and firefox

**Comment by zeeshanhyder** [comment]
Can you please send me the markup part, where you use this CSS file.
e.g. `<link rel='stylesheet' href='../..css'>`

Tip: in your `<link>` tag, add `type='text/css'` and then check and tell me.
Thanks.

**Comment by zeeshanhyder** [comment]
Seems more like browser issue, rather than with the functionality of the code. Closing.
